# config.yml v3.3
# you can now backup or share this file with your friends without revealing credentials

# application configuration
app:
  relay:
    # relay server url and connection timeout in milliseconds
    # comment server line out to disable relay
    server: https://snapchatreverse.jaku.tv
    timeout: 6000

  flag:
    # https://github.com/ptrumpis/snap-camera-signature-patch
    # web lens toggle
    # unlocks all lenses even those created after January 25, 2023
    # requires a patched binary with disabled signature checks
    enable_web_source: true

    # https://github.com/ptrumpis/snap-camera-signature-patch
    # custom lens toggle
    # unlocks access to customized lenses
    # requires a patched binary with disabled signature checks
    enable_custom_source: true

    # https://github.com/ptrumpis/snap-lens-cache-import
    # enable import of cached application lenses through special api
    # if you run a public server, you should set this to 'false'
    # otherwise anyone can upload files to your server
    enable_cache_import: true

    # https://github.com/ptrumpis/snap-lens-cache-import
    # enable import of customized/modiefed lenses through special api
    # if you run a public server, you should set this to 'false'
    # otherwise anyone can upload files to your server
    enable_custom_import: true

    # mirrors and downloads all your search results
    # comes with increased disk space usage
    # but helps to back up lenses in case they disappear
    mirror_search_results: false

    # ignore alternative media download
    # turning it on has no downside and saves alot of disk space
    # IGNORE_ALT_MEDIA takes precedence over IGNORE_IMG_SEQUENCE
    ignore_alt_media: true
    ignore_img_sequence: true

# media configuration
media:
  # show placeholder images to distinguish missing media files from broken links
  placeholder:
    thumbnail: false
    snapcode: false
    icon: false

# import configuration
import:
  # allow cache import and custom import to overwrite existing lenses
  allow_overwrite: true

  # store imported lenses as .zip archive or use original .lns format
  # if you run a public server, you should set this to 'true'
  # otherwise uploaded files will not be validated
  zip_archive: true

# search configuration
search:
  # Snap Lens Web Crawler settings for crawling https://snapchat.com/lens
  # Package: https://github.com/ptrumpis/snap-lens-web-crawler
  crawler:
    # connection timeout in milliseconds
    connectionTimeoutMs: 9000

    # delay between subsequent requests in milliseconds
    minRequestDelayMs: 100

    # cache time in seconds to speed up search results
    cacheTTL: 86400

    # set custom headers to prevent HTTP 403 errors
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36

  # caching is required to activate web lenses within search results
  # web caching requires 'app.flag.enable_web_source' to be 'true'
  web_cache:
    # standard time to live in seconds
    # web search results will expire after this time
    # 0 = infinity (memory usage will grow)
    ttl: 3600

    # time in seconds to check all data and delete expired search results
    check: 600

  # creator base url for displaying all lenses of a single creator
  # this feature requires 'app.flag.enable_web_source' to be 'true'
  creator_url: https://lensstudio.snapchat.com/creator/

  # supported lens share urls
  # this feature requires 'app.flag.enable_web_source' to be 'true'
  # paste an url and strip/remove any other non static http parameters
  # - mark/replace the 32 character lens identifier with {UUID}
  share_urls:
    - https://lens.snapchat.com/{UUID}
    - https://www.snapchat.com/lens/{UUID}
    - https://www.snapchat.com/unlock/?uuid={UUID}

# storage configuration
storage:
  # urls to be served from local storage
  # you can add or remove urls
  # an update is required if relay server changes
  urls:
    - https://app.snapchat.com
    - https://bolt-gcdn.sc-cdn.net
    - https://community-lens.storage.googleapis.com
    - https://lens-preview-storage.storage.googleapis.com
    - https://lens-storage.storage.googleapis.com
    - https://snapcodes.storage.googleapis.com
    - https://storage.googleapis.com
    - https://s3.amazonaws.com
    - https://snap-storage.jaku.tv
    - https://snapchatreverse.jaku.tv
