services:
  camera-kit-bridge:
    image: ptrumpis/snap-camerakit-bridge@sha256:2db205698617ca279548f9f327e3ebfc603af033aafe1dbcd4e770f8f1d25eeb
    profiles:
      - creator
    ports:
      - ${BRIDGE_LOCAL_PORT}:3000
    depends_on:
      - webapp
